# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-squid
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-squid is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-squid is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-squid.
# If not, see <https://www.gnu.org/licenses/>.

---

namespace: mafalb
name: squid
version: 0.1.0
readme: README.md

authors:
- Markus Falb <markus.falb@mafalb.at>

description: Ansible collection for squid

license:
- GPL-3.0-or-later

tags:
- squid
- proxy

dependencies: {}

repository: https://github.com/mafalb/ansible-collection-squid
documentation: https://github.com/mafalb/ansible-collection-squid
homepage: https://github.com/mafalb/ansible-collection-squid
issues: https://github.com/mafalb/ansible-collection-squid/issues

...
