# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-squid
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-squid is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-squid is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-squid.
# If not, see <https://www.gnu.org/licenses/>.

---

squid_state: present
squid_cfg_template: mafalb.squid.server.conf.j2

squid_cfg:

  ACLs:

    localnet:
      acltype: src
      ACEs:
      - comment: 'RFC 1122 "this" network (LAN)'
        value: 0.0.0.1-0.255.255.255
      - comment: RFC 1918 local private network (LAN)
        value: 10.0.0.0/8
      - comment: RFC 6598 shared address space (CGN)
        value: 100.64.0.0/10
      - comment: RFC 3927 link-local (directly plugged) machines
        value: 169.254.0.0/16
      - comment: RFC 1918 local private network (LAN)
        value: 172.16.0.0/12
      - comment: RFC 1918 local private network (LAN)
        value: 192.168.0.0/16
      - comment: RFC 4193 local private network range
        value: fc00::/7
      - comment: RFC 4291 link-local (directly plugged) machines
        value: fe80::/10

    SSL_ports:
      acltype: port
      ACEs:
      - value: 443

    Safe_ports:
      acltype: port
      ACEs:
      - value: 80
        comment: http
      - value: 443
        comment: https

    CONNECT:
      acltype: method
      ACEs:
      - value: CONNECT

...
