# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-squid
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-squid is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-squid is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-squid.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: Converge
  hosts: server_group
  roles:
  - role: mafalb.squid.server
    squid_cfg_template: squid.conf.j2
    squid_cfg:
      acl:
        myhosts:
        - src 127.0.0.1
        - src 192.168.0.0/16
        - src 10.0.0.0/8
        - src 172.16.0.0/12
      http_access:
      - allow myhosts
      - deny all
      shutdown_lifetime: 30 seconds # that i have something to grep in CI

- name: Converge client (Get Proxy IP)
  hosts: client_group
  pre_tasks:
    - name: Register proxy IP
      ansible.builtin.command:
        cmd: cat /proxyipv4.txt
      register: proxy_ipv4
      changed_when: false

- name: Converge client
  hosts: client_group
  environment:
    http_proxy: "{{ proxy_ipv4 }}:3128"
    https_proxy: "{{ proxy_ipv4 }}:3128"
  roles:
    - role: install_curl  # noqa syntax-check[specific]
...
