# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

squid_spool_dir: /var/spool/squid

squid_default_cfg:

  acl:

    localnet:
    - src 0.0.0.1-0.255.255.255 # RFC 1122 "this" network (LAN)
    - src 10.0.0.0/8            # RFC 1918 local private network (LAN)
    - src 100.64.0.0/10         # RFC 6598 shared address space (CGN)
    - src 169.254.0.0/16        # RFC 3927 link-local (directly plugged) machines
    - src 172.16.0.0/12         # RFC 1918 local private network (LAN)
    - src 192.168.0.0/16        # RFC 1918 local private network (LAN)
    - src fc00::/7              # RFC 4193 local private network range
    - src fe80::/10             # RFC 4291 link-local (directly plugged) machines

    SSL_ports: port 443

    Safe_ports:
    - port 80   # http
    - port 443  # https

    CONNECT: method CONNECT

  http_access:
  - deny !Safe_Ports
  - deny CONNECT !SSL_ports
  - allow localhost manager
  - deny manager
  - deny to_localhost
  - allow localhost
  - allow localnet
  - deny all

  http_port: 3128
  coredump_dir: "{{ squid_spool_dir }}" # Leave coredumps in the first cache dir

  refresh_pattern:
  - '^ftp 1440 20% 10080'
  - '^gopher 1440 0% 1440'
  - '-i (/cgi-bin/|\?) 0 0% 0'
  - '. 0 20% 4320'

squid:
  cfg: "{{ squid_default_cfg | combine(squid_cfg) }}"

...
