# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-squid
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-squid is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-squid is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-squid.
# If not, see <https://www.gnu.org/licenses/>.

---

dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -vv
  ansible-lint -v roles/*/vars/*.yml
  flake8 -v

platforms:
- name: ci-${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
  image: ${CI_REGISTRY}${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
  command: /lib/systemd/systemd
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-internal
  - name: molecule-external
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true
  groups:
  - server

- name: ci-client
  image: centos:7
  command: /lib/systemd/systemd
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
      stdout_callback: yaml
      bin_ansible_callbacks: true

  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
