# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Squid is present
  package:
    name: squid

- name: Debug squid_cfg_template
  debug:
    var: squid_cfg_template
  tags:
  - never
  - debug

- name: Check config
  assert:
    that:
    - squid.cfg.acl is defined
    - squid.cfg.http_access is defined
    - squid.cfg|type_debug == 'dict'

- name: Squid is configured
  template:
    src: "{{ squid_cfg_template }}"
    dest: /etc/squid/squid.conf
    mode: '644'
    backup: true
    validate: squid -k parse -f %s
  notify: Reload squid

- name: Squid is running
  service:
    name: squid
    state: started
    enabled: true
  register: _squid_has_started

...
