# vim: set ft=yaml ts=2 expandtab:
---

galaxy_info:
  author: Markus
  description: Ansible role server
  license: GPLv3
  min_ansible_version: 2.9

  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: EL
    versions:
    - 7
    - 8
  - name: Fedora
    versions:
    - 30
    - 31
  - name: Ubuntu
    versions:
    - xenial
    - bionic

  galaxy_tags:
  - server

dependencies: []

...
