# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

galaxy_info:
  author: Markus Falb <markus.falb@mafalb.at>
  description: Ansible role mafalb.squid.server
  license: GPLv3
  min_ansible_version: '2.9'

  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: EL
    versions:
    - '7'
    - '8'
  - name: Fedora
    versions:
    - '33'
    - '34'
  - name: Ubuntu
    versions:
    - bionic
    - focal
  - name: Debian
    versions:
    - stretch
    - buster

  galaxy_tags:
  - squid

dependencies: []

...
