# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '40 11 * * 5'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - c8s
        - alma8
        - rocky8
        - centos7
        - ubuntu20
        - ubuntu22

        ansible_version:
        - '2.14'
        - '2.15'

        include:

        - target: c8s
          image: quay.io/centos/centos:stream8

        - target: alma8
          image: quay.io/almalinux/almalinux:8

        - target: rocky8
          image: quay.io/rockylinux/rockylinux:8

        - target: centos7
          image: quay.io/centos/centos:7

        - target: ubuntu20
          image: docker.io/ubuntu:focal

        - target: ubuntu22
          image: docker.io/ubuntu:jammy

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_IMAGE: ${{ matrix.image }}
      CI_HOSTNAME: ci-${{ matrix.target }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: mafalb/workflows
          path: workflows
          ref: f-ansiblecollection  # FIX

      - name: Install Ansible
        uses: ./workflows/.github/actions/installansible
        with:
          extra_packages: 'molecule_podman,molecule'
          ref: dev  # FIX
          ansible_version: ${{ matrix.ansible_version }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ansible/collections/mafalb/squid

      - name: molecule default scenario
        working-directory: ansible_collections/mafalb/squid
        run: |
          source ~/.virtualenvs/ansible/bin/activate
          molecule test

      - name: molecule custom_template scenario
        working-directory: ansible_collections/mafalb/squid
        run: |
          source ~/.virtualenvs/ansible/bin/activate
          molecule test -s custom_template

      - name: molecule squid_cfg scenario
        working-directory: ansible_collections/mafalb/squid
        run: |
          source ~/.virtualenvs/ansible/bin/activate
          molecule test -s squid_cfg
...
