# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '40 11 * * 5'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos7
        - centos8

        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos7
          image: centos
          tag: 7

        - target: centos8
          image: centos
          tag: 8

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.image }}
      CI_CONTAINER_TAG: ${{ matrix.tag }}
      CI_CONTAINER_PRIVILEGED: true
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/squid

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/squid

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          repository: mafalb/ansible-collection-ansible
          path: ansible_collections/mafalb/ansible
          ref: dev

      - name: install dependencies
        run: ansible-galaxy collection install -r molecule/requirements.yml

      - name: install molecule
        run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test

...
