# vim: set ft=yaml ts=2 expandtab:
---

name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'
  pull_request:
  schedule:
    - cron: '40 11 * * 5'
  workflow_dispatch:
    inputs:
      targeted_branch:
        description: The name of the target branch on other repositories
        type: choice
        options:
          - dev
          - main

jobs:

  ci:
    if: ${{ ! (github.event.pull_request.head.repo.full_name == github.repository) }}
    uses: ./.github/workflows/ci-CI.yml
    with:
      targeted_branch: ${{ inputs.targeted_branch }}
...
