# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '40 11 * * 5'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos7
        - centos8
        - centosstream8
        - ubuntu-18.04
        - ubuntu-20.04
        - fedora32
        - fedora33
        - debian9
        - debian10


        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos7
          image: centos
          tag: 7

        - target: centos8
          image: centos
          tag: 8

        - target: centosstream8
          distribution: centos
          registry: "quay.io/centos/"
          version: stream8

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic

        - target: ubuntu-20.04
          distribution: ubuntu
          version: focal

        - target: fedora32
          distribution: fedora
          version: 32

        - target: fedora33
          distribution: fedora
          version: 33

        - target: debian9
          distribution: debian
          version: stretch

        - target: debian10
          distribution: debian
          version: buster


    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.image }}
      CI_CONTAINER_TAG: ${{ matrix.tag }}
      CI_REGISTRY: ${{ matrix.registry }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/squid

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/squid

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          repository: mafalb/ansible-collection-ansible
          ref: f_oldlint
          path: ansible_collections/mafalb/ansible

      - name: mv ansible
        run: |
          pwd
          ls -l ../
          mkdir -p ~/.ansible/collections/ansible_collections/mafalb
          mv ../ansible ~/.ansible/collections/ansible_collections/mafalb/

      - name: get mafalb.ansible
        if: false
        run: ansible-galaxy collection install mafalb.ansible

      - name: install molecule
        run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

      - name: check ansible version
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

      - name: molecule default scenario
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test

      - name: molecule custom_template scenario
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -s custom_template

      - name: molecule squid_cfg scenario
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -s squid_cfg

...
